import React, { useState } from 'react';
import { Project, ProjectModule } from '../../types';
import { 
  X, 
  Download, 
  Upload, 
  FileText, 
  Sparkles, 
  Check, 
  Copy, 
  Code, 
  Layers, 
  AlertCircle,
  FileCode
} from 'lucide-react';

interface ProjectImportExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  activeProject: Project;
  onImportModules: (newModules: ProjectModule[]) => void;
  onImportFullProject: (project: Project) => void;
}

export const ProjectImportExportModal: React.FC<ProjectImportExportModalProps> = ({
  isOpen,
  onClose,
  activeProject,
  onImportModules,
  onImportFullProject,
}) => {
  const [activeTab, setActiveTab] = useState<'import' | 'export'>('export');
  const [exportFormat, setExportFormat] = useState<'markdown' | 'ai-prompt' | 'json'>('markdown');
  const [importText, setImportText] = useState('');
  const [copied, setCopied] = useState(false);
  const [importError, setImportError] = useState<string | null>(null);
  const [importSuccess, setImportSuccess] = useState<string | null>(null);

  if (!isOpen) return null;

  // Generate Export Contents
  const generateMarkdownExport = () => {
    let md = `# Project Specification: ${activeProject.name}\n`;
    if (activeProject.description) {
      md += `> ${activeProject.description}\n\n`;
    }
    md += `*Generated by Headroom Focus OS on ${new Date().toLocaleDateString()}*\n\n---\n\n`;

    activeProject.modules.forEach((mod) => {
      const total = mod.doneItems.length + mod.missingItems.length;
      const pct = total > 0 ? Math.round((mod.doneItems.length / total) * 100) : 0;

      md += `## ${mod.name} ${mod.version ? `(\`${mod.version}\`)` : ''}\n`;
      md += `**Status:** ${mod.status.toUpperCase()} | **Completion:** ${pct}% (${mod.doneItems.length}/${total})\n\n`;
      if (mod.summary) md += `${mod.summary}\n\n`;
      if (mod.techStack && mod.techStack.length > 0) {
        md += `**Tech Stack:** ${mod.techStack.join(', ')}\n\n`;
      }

      md += `### Implemented Features (Done)\n`;
      if (mod.doneItems.length === 0) {
        md += `*None yet*\n`;
      } else {
        mod.doneItems.forEach((d) => {
          md += `- [x] ${d.title}\n`;
        });
      }
      md += `\n### Missing Deliverables (Todo)\n`;
      if (mod.missingItems.length === 0) {
        md += `*All planned items completed!*\n`;
      } else {
        mod.missingItems.forEach((m) => {
          md += `- [ ] ${m.title}\n`;
        });
      }
      if (mod.notes) {
        md += `\n*Notes:* ${mod.notes}\n`;
      }
      md += `\n---\n\n`;
    });

    return md;
  };

  const generateAiPromptExport = () => {
    let prompt = `You are an expert senior software engineer and architect assisting with the development of the project "${activeProject.name}".\n\n`;
    prompt += `Project Description: ${activeProject.description || 'N/A'}\n\n`;
    prompt += `Here is the current implementation status and breakdown of each module. For each module, notice the already completed features and the deliverables that are STILL MISSING:\n\n`;

    activeProject.modules.forEach((mod, idx) => {
      prompt += `========================================\n`;
      prompt += `MODULE ${idx + 1}: ${mod.name} [Status: ${mod.status}] ${mod.version ? `(${mod.version})` : ''}\n`;
      if (mod.summary) prompt += `Summary: ${mod.summary}\n`;
      if (mod.techStack?.length) prompt += `Stack: ${mod.techStack.join(', ')}\n`;
      prompt += `\nALREADY IMPLEMENTED:\n`;
      if (mod.doneItems.length === 0) prompt += `- None yet\n`;
      else mod.doneItems.forEach((d) => { prompt += `✓ ${d.title}\n`; });

      prompt += `\nSTILL MISSING & REQUIRED:\n`;
      if (mod.missingItems.length === 0) prompt += `- All items complete\n`;
      else mod.missingItems.forEach((m) => { prompt += `✗ [MISSING] ${m.title}\n`; });

      if (mod.notes) prompt += `\nSpecial Notes / Constraints: ${mod.notes}\n`;
      prompt += `\n`;
    });

    prompt += `========================================\n\n`;
    prompt += `YOUR MISSION:\n`;
    prompt += `1. Focus primarily on the modules in 'planning' or 'in-progress'.\n`;
    prompt += `2. For the MISSING deliverables, propose clear, concrete architectural designs and high-quality production code implementations.\n`;
    prompt += `3. Adhere to strict typing, maintainable structure, and defensive error handling.`;

    return prompt;
  };

  const generateJsonExport = () => {
    return JSON.stringify(activeProject, null, 2);
  };

  const getExportText = () => {
    switch (exportFormat) {
      case 'ai-prompt': return generateAiPromptExport();
      case 'json': return generateJsonExport();
      case 'markdown':
      default:
        return generateMarkdownExport();
    }
  };

  const handleCopyExport = () => {
    navigator.clipboard.writeText(getExportText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2200);
  };

  const handleDownloadFile = () => {
    const text = getExportText();
    let extension = '.md';
    let mime = 'text/markdown';
    if (exportFormat === 'json') {
      extension = '.json';
      mime = 'application/json';
    } else if (exportFormat === 'ai-prompt') {
      extension = '-ai-prompt.txt';
      mime = 'text/plain';
    }

    const filename = `${activeProject.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}-spec${extension}`;
    const blob = new Blob([text], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Parser for Markdown Spec or JSON
  const handleRunImport = () => {
    setImportError(null);
    setImportSuccess(null);

    if (!importText.trim()) {
      setImportError('Please paste Markdown or JSON to import.');
      return;
    }

    // Try parsing as JSON first
    if (importText.trim().startsWith('{')) {
      try {
        const parsed = JSON.parse(importText);
        if (parsed.name && Array.isArray(parsed.modules)) {
          onImportFullProject(parsed);
          setImportSuccess(`Successfully imported project "${parsed.name}" with ${parsed.modules.length} modules!`);
          setTimeout(onClose, 1500);
          return;
        } else if (Array.isArray(parsed)) {
          onImportModules(parsed);
          setImportSuccess(`Successfully imported ${parsed.length} modules!`);
          setTimeout(onClose, 1500);
          return;
        }
      } catch (err: any) {
        // Not JSON, fall back to Markdown parser
      }
    }

    // Parse Markdown Spec
    try {
      const lines = importText.split('\n');
      const parsedModules: ProjectModule[] = [];
      let currentModule: ProjectModule | null = null;

      for (let i = 0; i < lines.length; i++) {
        const rawLine = lines[i];
        const line = rawLine.trim();

        // Check for module header: ## or ###
        const headerMatch = line.match(/^#{1,3}\s+(.+)/);
        if (headerMatch) {
          const headerTitle = headerMatch[1].trim();

          // Ignore subheadings like "Done", "Implemented", "Missing"
          const isSectionSubheader = /^(implemented|done|what's done|missing|what's missing|todo|deliverables|specs)/i.test(headerTitle);

          if (!isSectionSubheader) {
            // Extract version if present in header, e.g. "Retention (v0.8.2)"
            let modName = headerTitle;
            let modVersion: string | undefined = undefined;
            const versionMatch = headerTitle.match(/\((v?[\d.]+)\)/i);
            if (versionMatch) {
              modVersion = versionMatch[1];
              modName = headerTitle.replace(/\((v?[\d.]+)\)/i, '').trim();
            }

            if (currentModule) {
              parsedModules.push(currentModule);
            }

            currentModule = {
              id: `mod-${Date.now()}-${parsedModules.length}`,
              projectId: activeProject.id,
              name: modName,
              summary: '',
              status: 'in-progress',
              version: modVersion,
              doneItems: [],
              missingItems: [],
              updatedAt: Date.now(),
            };
            continue;
          }
        }

        // If we don't have a module yet, create a default one
        if (!currentModule && line.length > 0 && !line.startsWith('#')) {
          currentModule = {
            id: `mod-${Date.now()}-default`,
            projectId: activeProject.id,
            name: 'Imported Module',
            summary: '',
            status: 'in-progress',
            doneItems: [],
            missingItems: [],
            updatedAt: Date.now(),
          };
        }

        if (currentModule) {
          // Check for Done checkbox: - [x] or * [x]
          const doneMatch = line.match(/^[-*]\s+\[x\]\s+(.+)/i);
          if (doneMatch) {
            currentModule.doneItems.push({
              id: `scope-${Date.now()}-${Math.random().toString(36).substr(2, 4)}`,
              title: doneMatch[1].trim(),
              completed: true,
              createdAt: Date.now(),
              completedAt: Date.now(),
            });
            continue;
          }

          // Check for Missing checkbox: - [ ] or * [ ]
          const missingMatch = line.match(/^[-*]\s+\[\s*\]\s+(.+)/);
          if (missingMatch) {
            currentModule.missingItems.push({
              id: `scope-${Date.now()}-${Math.random().toString(36).substr(2, 4)}`,
              title: missingMatch[1].trim(),
              completed: false,
              createdAt: Date.now(),
            });
            continue;
          }

          // Plain bullet point: treat as missing item
          const bulletMatch = line.match(/^[-*]\s+(.+)/);
          if (bulletMatch && !line.includes('[x]') && !line.includes('[ ]')) {
            currentModule.missingItems.push({
              id: `scope-${Date.now()}-${Math.random().toString(36).substr(2, 4)}`,
              title: bulletMatch[1].trim(),
              completed: false,
              createdAt: Date.now(),
            });
            continue;
          }

          // Plain text line: add to summary if short
          if (!line.startsWith('#') && line.length > 0 && !currentModule.summary) {
            currentModule.summary = line;
          }
        }
      }

      if (currentModule) {
        parsedModules.push(currentModule);
      }

      if (parsedModules.length === 0) {
        setImportError('No modules or checklists could be parsed from the provided text. Try markdown formatted with headers (### Module) and checkboxes (- [x] done, - [ ] missing).');
        return;
      }

      onImportModules(parsedModules);
      setImportSuccess(`Successfully imported ${parsedModules.length} module(s)!`);
      setTimeout(onClose, 1500);
    } catch (err: any) {
      setImportError(`Failed to parse: ${err.message}`);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs animate-in fade-in duration-150">
      <div 
        className="w-full max-w-2xl bg-offwhite-surface dark:bg-[#12151f] rounded-2xl border border-zinc-200 dark:border-zinc-800 shadow-2xl overflow-hidden flex flex-col max-h-[90vh]"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header with Tabs */}
        <div className="px-6 py-4 border-b border-zinc-200/80 dark:border-zinc-800/80 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="h-8 w-8 rounded-xl bg-brand-500/15 border border-brand-500/30 flex items-center justify-center text-brand-600 dark:text-brand-400">
              <Layers className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-base font-bold text-zinc-900 dark:text-white">
                Project Import & Export
              </h2>
              <p className="text-xs text-zinc-500 dark:text-zinc-400">
                Active project: <span className="font-semibold text-brand-600 dark:text-brand-400">{activeProject.name}</span>
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {/* Mode switch */}
            <div className="flex items-center bg-zinc-100 dark:bg-zinc-800/80 p-0.5 rounded-xl text-xs font-medium">
              <button
                onClick={() => setActiveTab('export')}
                className={`px-3 py-1 rounded-lg transition ${
                  activeTab === 'export'
                    ? 'bg-white dark:bg-zinc-700 text-zinc-900 dark:text-white shadow-xs font-semibold'
                    : 'text-zinc-500 hover:text-zinc-900 dark:hover:text-white'
                }`}
              >
                Export
              </button>
              <button
                onClick={() => setActiveTab('import')}
                className={`px-3 py-1 rounded-lg transition ${
                  activeTab === 'import'
                    ? 'bg-white dark:bg-zinc-700 text-zinc-900 dark:text-white shadow-xs font-semibold'
                    : 'text-zinc-500 hover:text-zinc-900 dark:hover:text-white'
                }`}
              >
                Import
              </button>
            </div>

            <button
              onClick={onClose}
              className="p-1 rounded-lg text-zinc-400 hover:text-zinc-700 dark:hover:text-zinc-200 hover:bg-zinc-100 dark:hover:bg-zinc-800 transition"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Content Body */}
        <div className="p-6 overflow-y-auto flex-1 space-y-4">
          {activeTab === 'export' ? (
            <>
              {/* Export Format Selector */}
              <div className="flex items-center justify-between flex-wrap gap-2">
                <div className="flex items-center gap-1.5 bg-zinc-100 dark:bg-zinc-900 p-1 rounded-xl text-xs">
                  <button
                    onClick={() => setExportFormat('markdown')}
                    className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg transition ${
                      exportFormat === 'markdown'
                        ? 'bg-white dark:bg-zinc-800 text-zinc-900 dark:text-white font-semibold shadow-xs'
                        : 'text-zinc-500 hover:text-zinc-900 dark:hover:text-white'
                    }`}
                  >
                    <FileText className="w-3.5 h-3.5 text-blue-500" />
                    <span>Markdown PRD</span>
                  </button>
                  <button
                    onClick={() => setExportFormat('ai-prompt')}
                    className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg transition ${
                      exportFormat === 'ai-prompt'
                        ? 'bg-white dark:bg-zinc-800 text-brand-600 dark:text-brand-300 font-semibold shadow-xs'
                        : 'text-zinc-500 hover:text-zinc-900 dark:hover:text-white'
                    }`}
                  >
                    <Sparkles className="w-3.5 h-3.5 text-brand-500" />
                    <span>AI Coding Prompt</span>
                  </button>
                  <button
                    onClick={() => setExportFormat('json')}
                    className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg transition ${
                      exportFormat === 'json'
                        ? 'bg-white dark:bg-zinc-800 text-zinc-900 dark:text-white font-semibold shadow-xs'
                        : 'text-zinc-500 hover:text-zinc-900 dark:hover:text-white'
                    }`}
                  >
                    <Code className="w-3.5 h-3.5 text-emerald-500" />
                    <span>Raw JSON</span>
                  </button>
                </div>

                <div className="flex items-center gap-2">
                  <button
                    onClick={handleCopyExport}
                    className={`px-3 py-1.5 rounded-xl border text-xs font-medium transition flex items-center gap-1.5 ${
                      copied
                        ? 'bg-emerald-500/20 text-emerald-600 dark:text-emerald-400 border-emerald-500/40'
                        : 'bg-white dark:bg-zinc-800 text-zinc-700 dark:text-zinc-200 border-zinc-200 dark:border-zinc-700 hover:bg-zinc-100 dark:hover:bg-zinc-700'
                    }`}
                  >
                    {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                    <span>{copied ? 'Copied!' : 'Copy to Clipboard'}</span>
                  </button>
                  <button
                    onClick={handleDownloadFile}
                    className="px-3 py-1.5 rounded-xl bg-brand-600 hover:bg-brand-500 text-white text-xs font-semibold shadow-sm transition flex items-center gap-1.5"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>Download</span>
                  </button>
                </div>
              </div>

              {/* Preview Box */}
              <div className="relative">
                <textarea
                  readOnly
                  rows={14}
                  value={getExportText()}
                  className="w-full text-xs font-mono p-4 rounded-xl bg-offwhite-subtle dark:bg-[#0c0e15] border border-zinc-200 dark:border-zinc-800 focus:outline-none text-zinc-800 dark:text-zinc-200 resize-none leading-relaxed select-all"
                />
              </div>
            </>
          ) : (
            <>
              {/* Import View */}
              <div className="space-y-3">
                <div className="p-3.5 rounded-xl bg-blue-500/10 border border-blue-500/20 text-blue-700 dark:text-blue-300 text-xs flex items-start gap-2.5">
                  <FileCode className="w-4 h-4 shrink-0 mt-0.5 text-blue-500" />
                  <div className="space-y-1">
                    <p className="font-semibold">Markdown Spec & Checklist Parser</p>
                    <p className="text-[11px] opacity-90 leading-relaxed">
                      Paste a Markdown file or draft with modules and checkboxes. Lines with <code className="bg-blue-500/20 px-1 py-0.5 rounded font-mono">- [x]</code> will be imported as <strong>Done</strong>, and <code className="bg-blue-500/20 px-1 py-0.5 rounded font-mono">- [ ]</code> will be imported as <strong>Still Missing</strong>.
                    </p>
                  </div>
                </div>

                <div className="relative">
                  <textarea
                    rows={12}
                    value={importText}
                    onChange={(e) => setImportText(e.target.value)}
                    placeholder={`### Retention Sample Module\nCohort retention and sample calculation engine\n- [x] Initial math curve model\n- [x] Mock generator\n- [ ] Cohort filter dropdown UI\n- [ ] CSV export endpoint\n\n### Billing Module\n- [x] Stripe integration\n- [ ] Invoice download`}
                    className="w-full text-xs font-mono p-4 rounded-xl bg-offwhite-subtle dark:bg-[#0c0e15] border border-zinc-200 dark:border-zinc-800 focus:outline-none focus:ring-2 focus:ring-brand-500 text-zinc-800 dark:text-zinc-200 placeholder:text-zinc-400 resize-none leading-relaxed"
                  />
                </div>

                {importError && (
                  <div className="p-3 rounded-xl bg-red-500/10 border border-red-500/30 text-red-600 dark:text-red-400 text-xs flex items-center gap-2">
                    <AlertCircle className="w-4 h-4 shrink-0" />
                    <span>{importError}</span>
                  </div>
                )}

                {importSuccess && (
                  <div className="p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-600 dark:text-emerald-400 text-xs flex items-center gap-2">
                    <Check className="w-4 h-4 shrink-0" />
                    <span>{importSuccess}</span>
                  </div>
                )}

                <div className="pt-2 flex items-center justify-end gap-2.5">
                  <button
                    type="button"
                    onClick={() => setImportText('')}
                    className="px-3.5 py-2 rounded-xl text-xs font-medium text-zinc-500 hover:text-zinc-800 dark:hover:text-zinc-200 transition"
                  >
                    Clear
                  </button>
                  <button
                    type="button"
                    onClick={handleRunImport}
                    className="px-4 py-2 rounded-xl text-xs font-semibold bg-brand-600 hover:bg-brand-500 text-white shadow-md shadow-brand-500/20 transition flex items-center gap-1.5"
                  >
                    <Upload className="w-3.5 h-3.5" />
                    <span>Parse & Import</span>
                  </button>
                </div>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
};
